/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.buscaCEP;
import controller.TelaCadastroAtendenteController;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author VANESSA
 */
public class TelaCadastroAtendenteView extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroAtendenteView
     */
    public TelaCadastroAtendenteView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCep = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldBairro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldRua = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldNumero = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldCidade = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldNacionalidade = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldCpf = new javax.swing.JFormattedTextField();
        botaoCancelar = new javax.swing.JButton();
        botaoCadastrar = new javax.swing.JButton();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldConfirmarSenha = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldSenha = new javax.swing.JPasswordField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuPrincipal = new javax.swing.JMenu();
        jMenuItemHome = new javax.swing.JMenuItem();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuAtendente = new javax.swing.JMenu();
        jMenuItemCadAten = new javax.swing.JMenuItem();
        jMenuItemDemAten = new javax.swing.JMenuItem();
        jMenuItemAltAten = new javax.swing.JMenuItem();
        jMenuItemListarAten = new javax.swing.JMenuItem();
        jMenuMedico = new javax.swing.JMenu();
        jMenuItemCadMed = new javax.swing.JMenuItem();
        jMenuItemDemMed = new javax.swing.JMenuItem();
        jMenuItemAltMed = new javax.swing.JMenuItem();
        jMenuItemListarMed = new javax.swing.JMenuItem();
        jMenuPaciente = new javax.swing.JMenu();
        jMenuItemCadPac = new javax.swing.JMenuItem();
        jMenuItemExcPac = new javax.swing.JMenuItem();
        jMenuItemAltPac = new javax.swing.JMenuItem();
        jMenuItemListarPac = new javax.swing.JMenuItem();
        jMenuItemHisPac = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Atendente - Tela de Cadastro de Atendente");
        setMinimumSize(new java.awt.Dimension(1200, 700));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(157, 246, 219));
        jPanel1.setAutoscrolls(true);
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 176));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo_transparente_1.png"))); // NOI18N

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user_1.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cadastro de Atendente");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(483, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(445, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(34, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel3)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel4.setText("Nome");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel5.setText("Confirmar Senha");

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel6.setText("CEP");

        try {
            jTextFieldCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldCep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextFieldCepMouseExited(evt);
            }
        });
        jTextFieldCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCepActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel7.setText("Bairro");

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel8.setText("Rua/Avenida");

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel9.setText("Número (6 dígitos, use 0 caso nulo)");

        try {
            jTextFieldNumero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("nº ######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel11.setText("Cidade");

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel10.setText("Nacionalidade");

        jTextFieldNacionalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNacionalidadeActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel12.setText("CPF");

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel13.setText("E-mail");

        try {
            jTextFieldCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        botaoCancelar.setBackground(new java.awt.Color(255, 51, 51));
        botaoCancelar.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        botaoCancelar.setForeground(new java.awt.Color(255, 255, 255));
        botaoCancelar.setText("Apagar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });

        botaoCadastrar.setBackground(new java.awt.Color(102, 255, 102));
        botaoCadastrar.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        botaoCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        botaoCadastrar.setText("Cadastrar");
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });

        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel14.setText("Senha");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel9)
                        .addComponent(jLabel8)
                        .addComponent(jLabel7)
                        .addComponent(jLabel6)
                        .addComponent(jLabel4)
                        .addComponent(jTextFieldCep)
                        .addComponent(jTextFieldBairro)
                        .addComponent(jTextFieldRua)
                        .addComponent(jTextFieldNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                        .addComponent(jTextFieldNome))
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(121, 121, 121)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(botaoCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(botaoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel11)
                                .addComponent(jTextFieldCidade)
                                .addComponent(jLabel10)
                                .addComponent(jTextFieldNacionalidade)
                                .addComponent(jLabel12)
                                .addComponent(jTextFieldCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE))))
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldConfirmarSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                    .addComponent(jTextFieldSenha))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(11, 11, 11)
                        .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botaoCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 153));
        jMenuBar1.setBorder(null);
        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.setMaximumSize(new java.awt.Dimension(100, 32769));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(56, 40));

        jMenuPrincipal.setBackground(new java.awt.Color(0, 0, 153));
        jMenuPrincipal.setForeground(new java.awt.Color(0, 204, 0));
        jMenuPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/folder.png"))); // NOI18N
        jMenuPrincipal.setText("Principal");
        jMenuPrincipal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPrincipalActionPerformed(evt);
            }
        });

        jMenuItemHome.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/chat-home.png"))); // NOI18N
        jMenuItemHome.setText("Home");
        jMenuItemHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHomeActionPerformed(evt);
            }
        });
        jMenuPrincipal.add(jMenuItemHome);

        jMenuItemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair-menu-2.png"))); // NOI18N
        jMenuItemSair.setText("Sair");
        jMenuItemSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuPrincipal.add(jMenuItemSair);

        jMenuBar1.add(jMenuPrincipal);

        jMenuAtendente.setBackground(new java.awt.Color(0, 0, 153));
        jMenuAtendente.setForeground(new java.awt.Color(0, 204, 0));
        jMenuAtendente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user_red.png"))); // NOI18N
        jMenuAtendente.setText("Atendente");
        jMenuAtendente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuAtendente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuAtendente.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        jMenuItemCadAten.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user_add.png"))); // NOI18N
        jMenuItemCadAten.setText("Cadastrar");
        jMenuItemCadAten.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemCadAten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadAtenActionPerformed(evt);
            }
        });
        jMenuAtendente.add(jMenuItemCadAten);

        jMenuItemDemAten.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user_delete.png"))); // NOI18N
        jMenuItemDemAten.setText("Demitir");
        jMenuItemDemAten.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemDemAten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDemAtenActionPerformed(evt);
            }
        });
        jMenuAtendente.add(jMenuItemDemAten);

        jMenuItemAltAten.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user_go.png"))); // NOI18N
        jMenuItemAltAten.setText("Alterar Dados");
        jMenuItemAltAten.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemAltAten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAltAtenActionPerformed(evt);
            }
        });
        jMenuAtendente.add(jMenuItemAltAten);

        jMenuItemListarAten.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/report_user.png"))); // NOI18N
        jMenuItemListarAten.setText("Listar");
        jMenuItemListarAten.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemListarAten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarAtenActionPerformed(evt);
            }
        });
        jMenuAtendente.add(jMenuItemListarAten);

        jMenuBar1.add(jMenuAtendente);

        jMenuMedico.setBackground(new java.awt.Color(0, 0, 153));
        jMenuMedico.setForeground(new java.awt.Color(0, 204, 0));
        jMenuMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user_gray.png"))); // NOI18N
        jMenuMedico.setText("Médico");
        jMenuMedico.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jMenuMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMedicoActionPerformed(evt);
            }
        });

        jMenuItemCadMed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user_add.png"))); // NOI18N
        jMenuItemCadMed.setText("Cadastrar");
        jMenuItemCadMed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemCadMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadMedActionPerformed(evt);
            }
        });
        jMenuMedico.add(jMenuItemCadMed);

        jMenuItemDemMed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user_delete.png"))); // NOI18N
        jMenuItemDemMed.setText("Demitir");
        jMenuItemDemMed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemDemMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDemMedActionPerformed(evt);
            }
        });
        jMenuMedico.add(jMenuItemDemMed);

        jMenuItemAltMed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user_go.png"))); // NOI18N
        jMenuItemAltMed.setText("Alterar Dados");
        jMenuItemAltMed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemAltMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAltMedActionPerformed(evt);
            }
        });
        jMenuMedico.add(jMenuItemAltMed);

        jMenuItemListarMed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/report_user.png"))); // NOI18N
        jMenuItemListarMed.setText("Listar");
        jMenuItemListarMed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemListarMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarMedActionPerformed(evt);
            }
        });
        jMenuMedico.add(jMenuItemListarMed);

        jMenuBar1.add(jMenuMedico);

        jMenuPaciente.setBackground(new java.awt.Color(0, 0, 153));
        jMenuPaciente.setForeground(new java.awt.Color(0, 204, 0));
        jMenuPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user.png"))); // NOI18N
        jMenuPaciente.setText("Paciente");
        jMenuPaciente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jMenuItemCadPac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user_add.png"))); // NOI18N
        jMenuItemCadPac.setText("Cadastrar");
        jMenuItemCadPac.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemCadPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadPacActionPerformed(evt);
            }
        });
        jMenuPaciente.add(jMenuItemCadPac);

        jMenuItemExcPac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user_delete.png"))); // NOI18N
        jMenuItemExcPac.setText("Excluir");
        jMenuItemExcPac.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemExcPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExcPacActionPerformed(evt);
            }
        });
        jMenuPaciente.add(jMenuItemExcPac);

        jMenuItemAltPac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user_go.png"))); // NOI18N
        jMenuItemAltPac.setText("Alterar Dados");
        jMenuItemAltPac.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemAltPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAltPacActionPerformed(evt);
            }
        });
        jMenuPaciente.add(jMenuItemAltPac);

        jMenuItemListarPac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/report_user.png"))); // NOI18N
        jMenuItemListarPac.setText("Listar");
        jMenuItemListarPac.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemListarPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarPacActionPerformed(evt);
            }
        });
        jMenuPaciente.add(jMenuItemListarPac);

        jMenuItemHisPac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/page_white_magnify.png"))); // NOI18N
        jMenuItemHisPac.setText("Histórico");
        jMenuItemHisPac.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemHisPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHisPacActionPerformed(evt);
            }
        });
        jMenuPaciente.add(jMenuItemHisPac);

        jMenuBar1.add(jMenuPaciente);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHomeActionPerformed
        //Cria uma janela principal
        TelaPrincipalAtendenteView principal = new TelaPrincipalAtendenteView();
        //Deixa ela visível
        principal.setVisible(true);
        //Fecha a janela atual sem acabar com a aplicação
        this.dispose();
    }//GEN-LAST:event_jMenuItemHomeActionPerformed

    private void jMenuItemCadMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadMedActionPerformed
        //Cria uma janela para cadastrar o médico
        TelaCadastroMedicoView cadMed = new TelaCadastroMedicoView();
        //Deixa ela visível
        cadMed.setVisible(true);
        //Fecha a janela atual sem acabar com a aplicação
        this.dispose();
    }//GEN-LAST:event_jMenuItemCadMedActionPerformed

    private void jMenuItemListarMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarMedActionPerformed
        //Cria uma janela para cadastrar o paciente
        TelaListarMedicoAView listMed = new TelaListarMedicoAView();
        //Deixa ela visível
        listMed.setVisible(true);
        //Fecha a janela atual sem acabar com a aplicação
        this.dispose();
    }//GEN-LAST:event_jMenuItemListarMedActionPerformed

    private void jTextFieldNacionalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNacionalidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNacionalidadeActionPerformed

    private void jMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPrincipalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuPrincipalActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        //Cria uma janela de login
        TelaLoginView login = new TelaLoginView();
        //Deixa ela visível
        login.setVisible(true);
        //Fecha a janela atual sem acabar com a aplicação
        this.dispose();
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemCadAtenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadAtenActionPerformed
        //Cria uma janela para cadastrar a atendente
        TelaCadastroAtendenteView cadAten = new TelaCadastroAtendenteView();
        //Deixa ela visível
        cadAten.setVisible(true);
        //Fecha a janela atual sem acabar com a aplicação
        this.dispose();
    }//GEN-LAST:event_jMenuItemCadAtenActionPerformed

    private void jMenuMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuMedicoActionPerformed

    private void jMenuItemCadPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadPacActionPerformed
        //Cria uma janela para cadastrar o paciente
        TelaCadastroPacienteView cadPac = new TelaCadastroPacienteView();
        //Deixa ela visível
        cadPac.setVisible(true);
        //Fecha a janela atual sem acabar com a aplicação
        this.dispose();
    }//GEN-LAST:event_jMenuItemCadPacActionPerformed

    private void jMenuItemDemAtenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDemAtenActionPerformed
        //Cria uma janela para demitir a atendente
        TelaDemitirAtendenteView demAten = new TelaDemitirAtendenteView();
        //Deixa ela visível
        demAten.setVisible(true);
        //Fecha a janela atual sem acabar com a aplicação
        this.dispose();
    }//GEN-LAST:event_jMenuItemDemAtenActionPerformed

    private void jMenuItemDemMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDemMedActionPerformed
        //Cria uma janela para demitir o médico
        TelaDemitirMedicoView demMed = new TelaDemitirMedicoView();
        //Deixa ela visível
        demMed.setVisible(true);
        //Fecha a janela atual sem acabar com a aplicação
        this.dispose();
    }//GEN-LAST:event_jMenuItemDemMedActionPerformed

    private void jMenuItemExcPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExcPacActionPerformed
        //Cria uma janela para excluir o paciente
        TelaExcluirPacienteView excluirPac = new TelaExcluirPacienteView();
        //Deixa ela visível
        excluirPac.setVisible(true);
        //Fecha a janela atual sem acabar com a aplicação
        this.dispose();
    }//GEN-LAST:event_jMenuItemExcPacActionPerformed

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        jTextFieldNome.setText("");
        jTextFieldEmail.setText("");
        jTextFieldCep.setText("");
        jTextFieldBairro.setText("");
        jTextFieldRua.setText("");
        jTextFieldNumero.setText("");
        jTextFieldCidade.setText("");
        jTextFieldNacionalidade.setText("");
        jTextFieldCpf.setText("");
        jTextFieldSenha.setText("");
        jTextFieldConfirmarSenha.setText("");
        jTextFieldBairro.setText("");
    }//GEN-LAST:event_botaoCancelarActionPerformed

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
        //Pega os dados
        String resultado = null;
        
        String nome = jTextFieldNome.getText();
        String email = jTextFieldEmail.getText();
        String cpf = jTextFieldCpf.getText();
        String cep = jTextFieldCep.getText();
        String bairro = jTextFieldBairro.getText();
        String rua = jTextFieldRua.getText();
        String numero = jTextFieldNumero.getText();
        String cidade = jTextFieldCidade.getText();
        String nacionalidade = jTextFieldNacionalidade.getText();
        String senha = new String(jTextFieldSenha.getPassword());
        String confirmarSenha = new String(jTextFieldConfirmarSenha.getPassword());
        try {
            //Tira os espaços
            resultado = new TelaCadastroAtendenteController().acaoBotaoCadastrar(
                nome.trim(),
                email.trim(),
                cpf.trim(),
                cep.trim(),
                bairro.trim(),
                rua.trim(),
                numero.trim(),
                cidade.trim(),
                nacionalidade.trim(),
                senha.trim(),
                confirmarSenha.trim()
            );
        } catch (Exception ex) {
            Logger.getLogger(TelaCadastroAtendenteView.class.getName()).log(Level.SEVERE, null, ex);
        }
        String mensagemSucesso = "Cadastro efetuado com sucesso. Seu id de login é ";
        if (resultado.length() >= mensagemSucesso.length()) {
                if (resultado.substring(0, mensagemSucesso.length()).equals(mensagemSucesso)) {
                        JOptionPane.showMessageDialog(null, resultado, "Sucesso ao cadastrar", JOptionPane.INFORMATION_MESSAGE);
                        botaoCancelar.doClick();
                } else {
                        JOptionPane.showMessageDialog(null, resultado, "Erro ao cadastrar", JOptionPane.WARNING_MESSAGE);
                }
        }
        else {
                JOptionPane.showMessageDialog(null, resultado, "Erro ao cadastrar", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botaoCadastrarActionPerformed

    private void jTextFieldCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCepActionPerformed

    private void jTextFieldCepMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldCepMouseExited
        buscaCEP b = new buscaCEP();
        String cep = jTextFieldCep.getText();
        try {
            String rua = b.getEndereco(cep);
            jTextFieldRua.setText(rua);
            String bairro = b.getBairro(cep);
            jTextFieldBairro.setText(bairro);
            String cidade = b.getCidade(cep);
            jTextFieldCidade.setText(cidade);
        } catch (IOException ex) {
            Logger.getLogger(TelaCadastroAtendenteView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextFieldCepMouseExited

    private void jMenuItemAltAtenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAltAtenActionPerformed
        //Cria uma janela para cadastrar o paciente
        TelaAlterarDadosAtendente altAten = new TelaAlterarDadosAtendente();
        //Deixa ela visível
        altAten.setVisible(true);
        //Fecha a janela atual sem acabar com a aplicação
        this.dispose();
    }//GEN-LAST:event_jMenuItemAltAtenActionPerformed

    private void jMenuItemAltMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAltMedActionPerformed
        //Cria uma janela para cadastrar o paciente
        TelaAlterarDadosMedico altMed = new TelaAlterarDadosMedico();
        //Deixa ela visível
        altMed.setVisible(true);
        //Fecha a janela atual sem acabar com a aplicação
        this.dispose();
    }//GEN-LAST:event_jMenuItemAltMedActionPerformed

    private void jMenuItemAltPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAltPacActionPerformed
        //Cria uma janela para cadastrar o paciente
        TelaAlterarDadosPaciente altPac = new TelaAlterarDadosPaciente();
        //Deixa ela visível
        altPac.setVisible(true);
        //Fecha a janela atual sem acabar com a aplicação
        this.dispose();
    }//GEN-LAST:event_jMenuItemAltPacActionPerformed

    private void jMenuItemListarAtenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarAtenActionPerformed
        //Cria uma janela para cadastrar o paciente
        TelaListarAtendenteAView listAten = new TelaListarAtendenteAView();
        //Deixa ela visível
        listAten.setVisible(true);
        //Fecha a janela atual sem acabar com a aplicação
        this.dispose();
    }//GEN-LAST:event_jMenuItemListarAtenActionPerformed

    private void jMenuItemListarPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarPacActionPerformed
        //Cria uma janela para cadastrar o paciente
        TelaListarPacientesAView listPac = new TelaListarPacientesAView();
        //Deixa ela visível
        listPac.setVisible(true);
        //Fecha a janela atual sem acabar com a aplicação
        this.dispose();
    }//GEN-LAST:event_jMenuItemListarPacActionPerformed

    private void jMenuItemHisPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHisPacActionPerformed
        //Cria uma janela para ver o histórico
        TelaVerHistoricoAView verHist = new TelaVerHistoricoAView();
        //Deixa ela visível
        verHist.setVisible(true);
        //Fecha a janela atual sem acabar com a aplicação
        this.dispose();
    }//GEN-LAST:event_jMenuItemHisPacActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAtendenteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAtendenteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAtendenteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroAtendenteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroAtendenteView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenuAtendente;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAltAten;
    private javax.swing.JMenuItem jMenuItemAltMed;
    private javax.swing.JMenuItem jMenuItemAltPac;
    private javax.swing.JMenuItem jMenuItemCadAten;
    private javax.swing.JMenuItem jMenuItemCadMed;
    private javax.swing.JMenuItem jMenuItemCadPac;
    private javax.swing.JMenuItem jMenuItemDemAten;
    private javax.swing.JMenuItem jMenuItemDemMed;
    private javax.swing.JMenuItem jMenuItemExcPac;
    private javax.swing.JMenuItem jMenuItemHisPac;
    private javax.swing.JMenuItem jMenuItemHome;
    private javax.swing.JMenuItem jMenuItemListarAten;
    private javax.swing.JMenuItem jMenuItemListarMed;
    private javax.swing.JMenuItem jMenuItemListarPac;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenu jMenuMedico;
    private javax.swing.JMenu jMenuPaciente;
    private javax.swing.JMenu jMenuPrincipal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JFormattedTextField jTextFieldCep;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JPasswordField jTextFieldConfirmarSenha;
    private javax.swing.JFormattedTextField jTextFieldCpf;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNacionalidade;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JFormattedTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldRua;
    private javax.swing.JPasswordField jTextFieldSenha;
    // End of variables declaration//GEN-END:variables
}
